server:
  port: 8081
  servlet:
    session:
      timeout: 30m
spring:
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: MyCluster
  application:
    name: gift-consumer

  main:
    allow-bean-definition-overriding: true
management:
  endpoint:
    web:
      exposure:
        include: "*"
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
  httpclient:
    enabled: true