server:
  port: 8081
  servlet:
    session:
      timeout: 30m
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.63.144.75:3306/gift?useUnicode=true&useSSL=false
    username: root
    password: root123
  session:
    store-type: redis
    redis:
      flush-mode: on_save
      namespace: spring:session
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        cluster-name: MyCluster
  application:
    name: gift-consumer

  main:
    allow-bean-definition-overriding: true
management:
  endpoint:
    web:
      exposure:
        include: "*"
feign:
  client:
    config:
      default:
        connectTimeout: 300000
        readTimeout: 300000
  httpclient:
    enabled: true
debug: true